language: r

warnings_are_errors: true

r:
  - release
  - devel

cache: packages

sudo: required

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  
r_packages:
  - rgdal
  - sf