language: r

warnings_are_errors: true

r:
  - release
  
cache: packages

sudo: required

dist: trusty
  
before_install:
  # spatial stack:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

