---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figure/",
  fig.height = 1
)
```

# spData 

Datasets for spatial analysis

### `sf`

- `baltimore` - House sales prices, Baltimore, MD 1978
- `cycle_hire` - 
- `cycle_hire_osm` - 
- `lnd` - 
- `wrld` - world country polygons
- `wheat` - Mercer and Hall wheat yield data

### `sp`

- `auckland` - Marshall's infant mortality in Auckland dataset
- `elect80` - 1980 Presidential election results
- `house` - Lucas county OH housing
- `SplashDams` - Data for Splash Dams in western Oregon
- `state.vbm` - US State Visibility Based Map

### `spdep`

- `afcon` - Spatial patterns of conflict in Africa 1966-78
- `boston` - Boston Housing Data
- `columbus` - Columbus OH spatial analysis data set
- `eire` - Eire data sets
- `nc.sids` - North Carolina SIDS data
- `NY_data` - New York leukemia data
- `used.cars` - US 1960 used car prices

### misc

- `getisord` - Getis-Ord remote sensing example data
- `hopkins` - Hopkins burnt savanna herb remains
- `huddersfield` - Prevalence of respiratory symptoms
- `jenks71` - Illinois 1959 county gross farm product value per acre

## Installation

Get the development version from github:

```R
devtools::install_github("nowosad/spData")
```

## Contributions

[Feel free to submit issues and enhancement requests.](https://github.com/Nowosad/spData/issues)
