library(rgdal)

auckland = readOGR("inst/shapes/auckland.shp")
baltim = readOGR("inst/shapes/baltim.shp")
boston_tracts = readOGR("inst/shapes/boston_tracts.shp")
mapview::mapview(boston_tracts)
columbus = readOGR("inst/shapes/columbus.shp")
cycle_hire = readOGR("inst/shapes/cycle_hire.geojson")
mapview::mapview(cycle_hire)
cycle_hire_osm = readOGR("inst/shapes/cycle_hire_osm.geojson")
mapview::mapview(cycle_hire_osm)
eire = readOGR("inst/shapes/eire.shp")
NY8_bna_utm18 = readOGR("inst/shapes/NY8_bna_utm18.gpkg")
mapview::mapview(NY8_bna_utm18)
NY8_utm18 = readOGR("inst/shapes/NY8_utm18.shp")
mapview::mapview(NY8_utm18)
sids = readOGR("inst/shapes/sids.shp")
wheat = readOGR("inst/shapes/wheat.shp")
world1 = readOGR("inst/shapes/world.gpkg")
world2 = readOGR("inst/shapes/world.shp")
mapview::mapview(world1)
mapview::mapview(world2)
